# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7155c83807d36b35d9d9ca8f7c7fd09b7eb2ee77e11091eb61b23da0984d7b8c312dd0969e5e0863e67eefca210d2b9b5b56ead699f6d840f27d4fddacff3407

test:
  secret_key_base: a872f8b6a19843b3a92b1ec5721a76ccdae650ec98cf5cc2020409618b65d3de0401f6d7f3f392cdb17c7f3a46c136f123d7466813baeaab68b3e76cda522376

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
